spring.application.name=Internship_Management

# ***************************************************************************#
# MySQL connection change port if your MySQL runs on different port
spring.datasource.url=jdbc:mysql://localhost:3306/internship_db // please change the url based on the port you are on ;
spring.datasource.username=root
spring.datasource.password=# Please add your MySQL password here
# ***************************************************************************#

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
